### PR TITLE
Ignore views setting

### PR DESCRIPTION
**Pull request by alextegelid**
I took a swing at #249 and I think I got a pretty good solution going. Please get back to me if there's anything you think I should change.

### CODE REVIEW

**Comment by pradyunsg** [comment]
Won't it be better if it checked a view-setting (`disable_color_highlighter`?) rather than checking/guessing on the basis of the name of the view?

PS: I would not include the typo-fix in this PR. It should be a separate PR. But that's just me. :smile:

**Comment by alextegelid** [comment]
I'm not familiar with view settings, but I'll look into it. In fact this is my first time programming against sublime texts api, my first lines of Python code and my first ever pull request :)

Thanks for the feedback on the typo. That sounds like good pull request practice. I'll remember that!

**Comment by pradyunsg** [comment]
Well, you can access it via `view.settings`. You can experiment in the Sublime Text Console. There view refers to the last-active view.

**Comment by alextegelid** [comment]
Would the view setting require other plugins to define for example "disable_color_highlighter"? Or could the user define that?

**Comment by Monnoroch** [comment]
This thing wont work. And don't even automergeble. And the way to do it is not by disabling CH, but by maintaining multiple modified color schemes for each in use.
I'm working on it.

**Comment by pradyunsg** [comment]
@Monnoroch 
I differ. There's merit here. Some people (if there's others like me) won't want to have colours highlighted certain syntaxes (like in git-diff etc). This PR was on road to adressing that. While it won't fix the linked issue, it does make sense to me to allow the colour-scheme to be disabled via some setting on a view...

@alextegelid 
No. You can define it in the Syntax-Specific Settings or even in Preferences.sublime-settings

**Comment by pradyunsg** [comment]
@alextegelid 
No. You can define it in the Syntax-Specific Settings or even in Preferences.sublime-settings

**Comment by stoivo** [comment]
:+1:

**Comment by alextegelid** [comment]
Thanks for explaining view settings for me @pradyunsg. Now that I understand that better I apologize for stating that this would solve issue 249. It clearly doesn't.

@Monnoroch While I think you could have used a nicer tone towards someone who's trying to help, I understand why you turned down the request.

**Comment by Monnoroch** [comment]
Anybody interested, could you please test my implementation from branch v7.2 of this repo? (for now, ST3 only).

@alextegelid Never ment to be impolite, sorry, if I somehow offensed you. I'm not a native english speaker.

**Comment by alextegelid** [comment]
It's all right, thanks for explaining. 

I'll try 7.2 tomorrow evening. Thanks for working on a solution.

**Comment by pradyunsg** [comment]
Me! :hand:

**Comment by alextegelid** [comment]
7.2 seems to solve my issue really nice!
:+1: from me!

Now: http://cl.ly/2v0f3u0T1N3i
Before: http://cl.ly/image/2e0S2e3F3r0V

**Comment by Monnoroch** [comment]
Ok, but the real question is: did I break anything else? =)

**Comment by alextegelid** [comment]
Haha! I'll run this for a while and keep my eyes open

**Comment by Monnoroch** [comment]
Thanks.

**Comment by pradyunsg** [comment]
Me too!

*whispers automated testing*

**Comment by Monnoroch** [comment]
@pradyunsg This is an open source project! You coud contribute, if you wish.

**Comment by pradyunsg** [comment]
Sure!

**Comment by stoivo** [comment]
:+1: :sparkles:

**Comment by pradyunsg** [comment]
Working well till now. :smile: No perceivable lag either.

**Comment by Monnoroch** [comment]
Good job, me!

**Comment by pradyunsg** [comment]
Good job @Monnoroch!

**Comment by alextegelid** [comment]
Good job indeed @Monnoroch! Thanks for this fix aswell as maintaining this plugin in general 👌🏼

**Comment by stoivo** [comment]
:sparkles:

**Pull request closed without merging**
