### PR TITLE
updates osx color picker

### PR DESCRIPTION
**Pull request by thematthopkins**
This gets the color picker working on OSX.  Built from:
https://github.com/thematthopkins/color-pick/tree/sublime_color_highlighter_compat

### CODE REVIEW

**Comment by Monnoroch** [comment]
Could you add the source code to the repo?

**Comment by Monnoroch** [comment]
There is also a problem with the fact, that CH works with RGBA as it's format and the command line arguments for this program won't match.

**Comment by thematthopkins** [comment]
I updated the color picker to work w/ alphas, and trimmed out some of the unused options.

Thanks for the awesome plugin!

**Comment by Monnoroch** [comment]
So then could you maby change the readme then, so I can look what the new interface is?

**Comment by Monnoroch** [comment]
Even better!
So, my current binary has this API (https://github.com/Monnoroch/ColorHighlighter/blob/master/ColorPicker/qt/main.cpp):
Input:
./colorpicker #FFFFFFFF
Output:
#AAAAAAAA or CANCEL, if the user had closed the window.


It would be perfect, if you could make yours compatible, that way I dont have to chenge the python code.

**Comment by thematthopkins** [comment]
Good call on the readme.  The executable is compatible + tested using the existing Color Highlighter version.  I just updated the readme.  For cancels, it leaves stdout empty, but Color Highlighter seems to handle that condition correctly.

**Comment by Monnoroch** [comment]
Thanks!

**Pull request merged**
