### PR TITLE
Report UnicodeDecodeErorrs in reading files instead of crashing.

### PR DESCRIPTION
**Pull request by Cybolic**
Fix for #288.

### CODE REVIEW

**Comment by Monnoroch** [comment]
This is like the best bug report ever!
But, to be sure, what exactly happens if the exception is thrown? I mean yes, it prints the message, but what then? Does the rest of the system work normally?

**Comment by Cybolic** [comment]
Thanks :)
After it throws the error it returns the file contents as an empty string, so I would assume the file gets no highlighting. I admit I didn't actually check how the file it crashed on appears after the fix as it's a file open in a different project that doesn't deal with colour, but I'll check when I get back to my workstation; the rest of the open files display as normal though.

**Comment by Cybolic** [comment]
Highlighting works in the affected file, so I assume only variables won't be picked up. Certainly better than none of the files working :)

**Comment by Monnoroch** [comment]
Thanks!
Although, it would be better to solve the problem altogether, it's still better, then an exception.

**Comment by Monnoroch** [comment]
I fixed this behaviour lots of times, but every time it happens again.
Python 3 supposed to solve this problem, but somehow it continues to break.

**Comment by Cybolic** [comment]
Maybe a wrapper function for file reading calls is a solution? E.g. try reading in unicode and fall back to trying a list of common encodings afterwards? (possibly a list like this, in order: http://w3techs.com/technologies/overview/character_encoding/all)

I can look at it in a new branch if you'd like :)

**Comment by Monnoroch** [comment]
But are you sure the problem is because your file isn't in utf8?
It seems highly unlikely to me.

**Comment by Cybolic** [comment]
Yup, absolutely sure. It's in iso8859-1 (latin-1); changing it to utf8 makes the problem disappear.
I've updated the branch to try every codec supported by Python in the order listed in the link above and tested it with a few files, disabling various codecs along the way to try to catch most situations. It works well.
Another option could be to use something like chardet or libmagic to get a better guess at the correct encoding and _then_ falling back to trying them all, but that's another dependency, so that's up to you.

**Comment by Monnoroch** [comment]
Oh, well, I'm a linux user and haven't seen non-utf8 files for ages :)

**Comment by Cybolic** [comment]
Same here ;) This one's from an old project of mine that I recently downloaded from an FTP server that apparently changed the codec.

**Pull request merged**
