### PR TITLE
Updated Color Picker for Windows

### PR DESCRIPTION
**Pull request by zmLGBBM**
Thanks to: @cyotek for his amazing `ColorPicker`. (Notice: it runs on .NET Framework 3.5)

Now we can select color, pick color from anywhere in the screen, change alpha channel,  load and save palettes etc.. I wrote a wrapper for it so that it can work with `ColorHighlighter`. 
default

### CODE REVIEW

**Comment by Monnoroch** [comment]
Thanks, this is awesome!
Although I would really wish, that you woldn't edit the python code and instead made the .NET program interface compliant.

**Comment by zmLGBBM** [comment]
@Monnoroch Oh yeah, that's good too. I'll do this tomorrow.

**Comment by Monnoroch** [comment]
Oh, I see, you made it to copy several files.
Did you test it on linux?

**Comment by zmLGBBM** [comment]
@Monnoroch Sorry, but I just have windows installed on my machine. I'll wrote another **single-file** wrapper tomorrow so it won't need to modify the **py** file then.

**Comment by zmLGBBM** [comment]
@Monnoroch That should work fine on Linux though, since all I did is change the `string literal` to `[string literal]`. Could someone test it?

**Comment by Monnoroch** [comment]
I could, but not today, so if you can pack it all into one binary, that'll be very good!

**Comment by zmLGBBM** [comment]
@Monnoroch This PR should work fine now.

**Comment by Monnoroch** [comment]
Thanks!

**Pull request merged**
